version: "3.8"
services:
 mongodb_product:
   image: "mongo:latest"
   container_name: mongodb_product
   ports:
    - 27017:27017
 product_catalog_mongodb: 
   image: "jayaramana/product_catalog_mongodb:v1.0"
   container_name: product_catalog_mongodb
   ports:
    - 8006:8006
   links:
    - mongodb_product